export const LABELS = {
  app: {
    name: "Antigravity",
    decisionLogic: "投資判定のロジック",
    editTransaction: "取引の編集",
    newTransaction: "新規取引",
  },

  sections: {
    quickActions: "クイックアクション",
    todayTasks: "今日の要対応",
    priceUpdate: "価格更新",
    stockUpdate: "株式・投信",
    fundUpdate: "投資信託",
    marketInput: "市況・指数",
    settings: "システム設定",
    journal: "ジャーナル",
    pnl: "損益通算パネル",
    summaryNotifications: "要約・通知設定",
    assets: "資産・トリガー管理",
  },

  summary: {
    totalAssets: "総資産",
    cashOnHand: "手元現金",
    buyCandidates: "買付候補",
    sellCandidates: "売却候補",
    stalePrices: "価格未更新",
    plannedOrders: "仮注文",
  },

  asset: {
    currentPrice: "現在値",
    closingPrice: "終値",
    officialPrice: "基準価額",
    referencePrice: "参考価格",
    updateTime: "更新時刻",
    priceSource: "取得元",
    holdingQty: "保有量",
    averageCost: "平均取得",
    valuation: "評価額",
    unrealizedPnL: "含み損益",
    realizedPnL: "実現損益",
    basePrice: "基準価格",
    decisionBand: "可変判断帯",
    environmentScore: "環境スコア",
    reason: "理由",
    difference: "差",
    type: "取引種別",
    date: "日付",
    status: "ステータス",
    quantity: "数量",
    price: "価格",
    fee: "手数料",
    tax: "税金",
    note: "メモ / 理由",
    ordinaryDist: "普通分配金 (実益)",
    specialDist: "特別分配金 (元本払戻)",
  },

  status: {
    buyCandidate: "買付候補",
    sellCandidate: "売却候補",
    watch: "様子見",
    hold: "ホールド継続",
    pending: "保留",
    sellPriority: "売却優先",
    avoid: "回避",
    sellApproaching: "売却接近",
  },

  environment: {
    tailwind: "追い風",
    slightlyTailwind: "やや追い風",
    neutral: "中立",
    slightlyHeadwind: "やや逆風",
    headwind: "逆風",
  },

  source: {
    synced: "同期済",
    api: "同期済",
    manual: "手動",
    preview: "確認前",
    stale: "古い値",
  },

  actions: {
    confirm: "確定",
    cancel: "キャンセル",
    save: "保存",
    saveAll: "まとめて保存",
    autoSync: "AUTO SYNC",
    manualPriceUpdate: "手動価格更新",
    addTrigger: "＋ 条件を追加",
    inputTransaction: "取引を入力",
    saveEndpoint: "Save Endpoint",
    clearLogs: "Clear Logs",
    nuclearReset: "Nuclear Reset",
    saveMidday: "前場の値を保存",
    saveClose: "大引けの値を保存",
    apply: "適用",
    discard: "破棄",
    understand: "了解しました",
    register: "登録する",
    saveChanges: "変更を保存する",
  },

  trigger: {
    buy: "買",
    sell: "売",
    stopped: "停止中",
    active: "有効",
    basePrice: "基準価格",
    noActiveTrigger: "有効トリガーなし",
    waiting: "待機",
    approaching: "接近",
    reached: "到達",
    pending: "保留",
    completed: "実行済み",
    gte: "以上",
    lte: "以下",
  },

  messages: {
    importConfirm: "現在のすべてのデータが上書きされます。よろしいですか？",
    importSuccess: "インポートが完了しました！",
    importErrorFormat: "Antigravityのバックアップファイルではないようです。形式が異なります。",
    importErrorRead: "ファイルの読み込みに失敗しました。正しいJSONファイルを選択してください。",
    inputErrorPositive: "閾値と数量は正の数値で入力してください。",
    resetConfirm: "本当にすべてのデータを初期化しますか？",
    copySuccess: "件名と本文をクリップボードにコピーしました！",
    clearSummaryConfirm: "要約履歴をクリアしますか？",
  },

  transaction: {
    type: "種別",
    status: "状態",
    buy: "買付",
    sell: "売却",
    distribution: "分配金",
    adjustment: "残高調整",
    planned: "予定",
    confirmed: "確定",
    cancelled: "取消",
    applied: "反映済",
  },
} as const;
